### ISSUE TITLE
ModelState.IsValid  in UserController.cs (is ButtonsController)

### ISSUE THREAD

**Issue by kiquenet** [ajsaulsberry/BlipCo#1]
`ModelState.IsValid` is always **false** for:

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "UserID,Username")] User user, float? answer)
        {
            if (ModelState.IsValid && answer.HasValue)

**Comment by ajsaulsberry** [comment]
No, no it's not. Certainly not with the information you've provided. Perhaps you should look at your view model?
